services:

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883 # MQTT without TLS
      - 8883:8883 # MQTT with TLS
      - 9011:9011 # websocket
    volumes:
      - ./mosquitto-data/config:/mosquitto/config
      - ./mosquitto-data/data:/mosquitto/data
      - ./mosquitto-data/log:/mosquitto/log
      - ./mosquitto-data/certs:/home/certs

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Portugal
    ports:
      - 1880:1880
    volumes:
      - ./node-red-data:/data

  postgres-db:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=health
  
  app:
      build: ./app-data/
      ports:
        - "8000:8000"